name: 'Releaseter'
description: 'Automate Release Draft generation with Releaster. Save time and ensure accuracy.'
branding:
  icon: git-pull-request
  color: orange

inputs:
  github-token:
    required: true
    description: "The token used to operate on the GitHub repository."
  config-path:
    default: "releaseter.yml"
    description: "The path to the configuration file."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'JZGoopi/releaseter'
        path: 'JZGoopi/releaseter'
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.19'
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        JZGOOPI_REPEASETER_CONFIG_PATH: ${{ inputs.config-path }}
        JZGOOPI_PATH: ${{ github.workspace }}/JZGoopi
        JZGOOPI_REPEASETER_WS_PATH: ${{ github.workspace }}/JZGoopi/releaseter
      run: |
        cd $JZGOOPI_REPEASETER_WS_PATH
        if [ "${{ runner.os }}" = "Linux" ]; then
          ./bin/app-linux-amd64
        else
          go mod tidy
          go run ./main.go
        fi
        rm -rf $JZGOOPI_PATH
