name: 'releaseter'
description: |
  Releaster is a GitHub Action that automatically generates a Release Draft by retrieving all Pull Requests from your last Release to the current time. You can customize the version number, tag, title, and content of the Release Draft by setting input parameters.
  This Action saves you time in writing Release Drafts while ensuring their accuracy and completeness.

inputs:
  github-token:
    required: true
    description: "The token used to operate on the GitHub repository."
  config-path:
    default: "releaseter.yml"
    description: "The path to the configuration file."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'JZGoopi/releaseter'
        path: 'JZGoopi/releaseter'
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.19'
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        JZGOOPI_REPEASETER_CONFIG_PATH: ${{ inputs.config-path }}
        JZGOOPI_PATH: ${{ github.workspace }}/JZGoopi
        JZGOOPI_REPEASETER_WS_PATH: ${{ github.workspace }}/JZGoopi/releaseter
      run: |
        cd $JZGOOPI_REPEASETER_WS_PATH
        if [ "${{ runner.os }}" = "Linux" ]; then
          ./bin/app-linux-amd64
        else
          go mod tidy
          go run ./main.go
        fi
        rm -rf $JZGOOPI_PATH
