name: Uh-oh, I Found a Bug
description: Report a bug so I can squash it!
title: "[Bug]: "
labels: ["bug"]
assignees:
  - JZGoopi
body:
  - type: textarea
    id: summary
    attributes:
      label: Quick and Dirty Summary
      description: Give me a brief rundown of the issue.
      placeholder: "What's up, bug?"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Software Version
      description: Which version of our software are you running?
      options:
        - "1"
        - "1.0.0"
    validations:
      required: true

  - type: input
    id: reproduction-link
    attributes:
      label: Link to Minimal Reproduction
      description: Got a link that'll help me understand what's happening?
      placeholder: "https://www.pornhub.com"
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: What do I need to do to see the bug in action?
      placeholder: |
        1. Click the link
        2. Pick up a piece of tissue paper
        3. Wipe off sweat.
        4. ...

  - type: textarea
    id: expected-result
    attributes:
      label: What Should Happen
      description: What did you expect to happen instead?
      placeholder: "I thought my sweat was transparent"

  - type: textarea
    id: actual-result
    attributes:
      label: What Actually Happened
      description: What actually went down?
      placeholder: "It seems to be a bit white-ish."

  - type: textarea
    id: other
    attributes:
      label: Anything Else I Should Know?
      description: Got any other info that might help me fix the issue? GitHub Actions config, project directory structure, Releaster.yml settings, etc.
      placeholder: |
        Here's my Releaster.yml setup!

        ```yaml
        time-location: 'metaverse'
        ```

        **Your code is so buggy that even my great-grandmother could write better!**
