package consts

const (
	TIME_WORKTIME = "{{ $TIME_WORKFLOW }}"

	VERSION_NEXT_MAJOR = "{{ $VERSION_NEXT_MAJOR }}"
	VERSION_NEXT_MINOR = "{{ $VERSION_NEXT_MINOR }}"
	VERSION_NEXT_PATCH = "{{ $VERSION_NEXT_PATCH }}"

	EMPTY = "{{ $EMPTY }}"
)

func GetVersionPlaceholders() [3]string {
	return [3]string{VERSION_NEXT_MAJOR, VERSION_NEXT_MINOR, VERSION_NEXT_PATCH}
}
